### ISSUE TITLE
How to eable delivery receipt and message ID

### ISSUE THREAD

**Issue by shamera** [onlinecity/php-smpp#12]
Hi,

I need to know how to enable delivery receipt and get message id for particular sms. it's better if you can tell me how to amend this to your example in basic send sms code.

**Comment by pablosky** [comment]
ill like to get just to id of the message sent , any clues please am changing library cos the old one didnt had , dlr or message id supported

**Comment by ruturaaj** [comment]
Well, I know this is quite old thread and I'm responding to this thread some 4 years later... wow! :-) 

The `$smpp->sendSMS` method of `smppclient.class.php` returns Message ID. If you want to get more details like Message ID, you will need to change `submit_sm` to return an array of fields you want. The `response` contains following fields... id, status, sequence, body. 

At the time of writing this comment. the `submit_sm` returns `$response->body`. You may build an array like...

```
$result = array($response->id, $response->status, $response->sequence, $response->body);
return $result;
```
