### ISSUE TITLE
no MSG_DONTWAIT in PHP 5.* for windows

### ISSUE THREAD

**Issue by anton0xf** [onlinecity/php-smpp#13]
Because of bug https://bugs.php.net/bug.php?id=48326 line sockettransport.class.php:327 fails on windows.

**Comment by duedal** [comment]
Replacing MSG_DONTWAIT with MSG_WAITALL is a behavior change, and could introduce other issues with connection maintenance. Besides I don't think it's going to work on windows with the sockets extension.
