### ISSUE TITLE
Queries on usage: Persistent connection for both read and write

### ISSUE THREAD

**Issue by tester5** [onlinecity/php-smpp#14]
I've reworded my original query so hopefully it is clearer (please let me know if not).

I would like to set up a persistent connection for both transmitter and receiver so I can send and receive sms messages without having to continually open and close connections.  I understand there is the ENQUIRE_LINK command. Though am not sure how to go about this.

If I am to set up a persistent connection is the following reasonable:

1) Have a separate process/class that manages Socket Transport connections.  Have this process run every 30 seconds and issue the ENQUIRE_LINK command. If a timeout is reached, close the existing Socket Transport connection and create a new Socket Transport connection.

2) Then have a send_sms and read_sms function that uses the existing (managed) Socket Transport connection and performs bind/unbind only to allow for multiple sessions (using sequence numbers) based on a windows size of say 50 SMS messages.

Would this approach work? And is it ideal?

Hope you can assist with my queries.

Many thanks.

**Comment by duedal** [comment]
We do have an open source implementation at [php-smpp-worker](https://github.com/onlinecity/php-smpp-worker) you can look at for inspiration
