### ISSUE TITLE
TSocket Bug on PHP 5.3 on Windows Plateform

### ISSUE THREAD

**Issue by ihtisham20** [onlinecity/php-smpp#19]
TSocket Bug on PHP 5.3 on Windows Platform... Not sure if this is known Issue. Any Remedy?  

This happens for receive a SMS (or delivery receipt) code only... Very strange.

PHP Fatal error:  Uncaught exception 'TException' with message 'TSocket: Could not connect to 110.34.37.51:28555 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 [10060])'

**Comment by duedal** [comment]
Sounds like a firewall issue, make sure you can connect, try ie. ```telnet 110.34.37.51 28555```.
