### ISSUE TITLE
UDH parameter is not retriving with the results

### ISSUE THREAD

**Issue by nimeshrmr** [onlinecity/php-smpp#22]
We want to use this library to access messages with multiple message parts. But we can't find the existence of the UDH parameter with the results.

Currently, we are receiving the value 0 for esmClass key. Ideally we should be retrieving message Type and UDH value for this key.

What the modifications required for accessing UDH parameter?

**Comment by duedal** [comment]
The UDH will be part of the $message, look for the UDHI indicator in the ESM class field, and if set get the UDH from $message.
