### ISSUE TITLE
Fatal error: Uncaught exception 'SmppException' with message 'Failed to read reply to command: 0x4' in smppclient.class.php:619 

### ISSUE THREAD

**Issue by aktiwers** [onlinecity/php-smpp#27]
Hi there,

First thanks a lot for a great smpp lib, that I have been using for some time now. All of a sudden I'm getting this error:

    Fatal error: Uncaught exception 'SmppException' with message 'Failed to read reply to command: 0x4' in /var/www/CRM/classes/smppclient.class.php:619

    Stack trace: #0 /var/www/CRM/classes/smppclient.class.php(391): SmppClient->sendCommand(4, '???SENDERIDHERE???45302...') #1 /var/www/CRM/classes/smppclient.class.php(339): SmppClient->submit_sm(Object(SmppAddress), Object(SmppAddress), 'SMSMESSEGAGE HERE...', '', 0) 
    #2 /var/www/CRM/sendSMS.php(65): SmppClient->sendSMS(Object(SmppAddress), Object(SmppAddress), 'SMSMESSEGAGE HERE...', '') #3 {main} thrown in /var/www/CRM/classes/smppclient.class.php on line 619

Can you help me figure out whey I am getting this? 

Im using it like this:

		$transport = new SocketTransport(array('smpp.COMPANYNAMEHERE.dk'),2775);
		$transport->setRecvTimeout(10000);
		$smpp = new SmppClient($transport);
	// Open the connection
		$transport->open();
		$smpp->debug = true;
		$transport->debug = true;
		$smpp->bindTransmitter("MYUSERNAMEHERE","MYPASSWORDHERE");
		// Optional connection specific overrides
		SmppClient::$sms_null_terminate_octetstrings = false;
		SmppClient::$csms_method = SmppClient::CSMS_PAYLOAD;
		//SmppClient::$sms_registered_delivery_flag = SMPP::REG_DELIVERY_SMSC_BOTH;
		
		//Besked til kunde
		$beskedfirst = stripslashes(strip_tags($_POST['message2']));
		//gem SMS i db
		$mysql->gemSMS($barid['Barid'], $beskedfirst, "0");
		$kundedata=$mysql->HentKundeTlf('vip', $barnavn);
			foreach ($kundedata as $tlf => $value) {

				 //erstat alle $navn med kundens rigtige navn i SMS beskeden - tilføj Afmeld besked
				$besked = str_replace('$navn', ucfirst($value['fornavn']), $beskedfirst)." - Afmeld skriv: Opsig ".$barid['Barid']." til XXX";
				
				if (strlen($value['tlf']) == 8) {
						
					// Prepare message
					$tlfnr = "45".$value['tlf'];
					$message = $besked;
					$encodedMessage = GsmEncoder::utf8_to_gsm0338($message);
					$from = new SmppAddress($afsender,SMPP::TON_ALPHANUMERIC);
					$to = new SmppAddress($tlfnr,SMPP::TON_INTERNATIONAL,SMPP::NPI_E164);

					// Send
					$smpp->sendSMS($from,$to,$encodedMessage,'');

					$sendt[] = array('tlf' => $tlfnr);
				}

			}
			// Close connection
			$smpp->close();

**Comment by duedal** [comment]
You need to periodically send an enquire link message to keep the connection alive. Consult the documentation of your SMPP provider.
