### ISSUE TITLE
Delivery Receipt Format

### ISSUE THREAD

**Issue by mpapec** [onlinecity/php-smpp#29]
Regarding validating regex,

		$numMatches = preg_match('/^id:([^ ]+) sub:(\d{1,3}) dlvrd:(\d{3}) submit date:(\d{10,12}) done date:(\d{10,12}) stat:([A-Z]{7}) err:(\d{2,3}) text:(.*)$/si', $this->message, $matches);

http://docs.nimta.com/SMPP_v3_4_Issue1_2.pdf is not too specific regarding number of spaces, so is it possible that correct receipt has "err: 0"? (note space between colon and zero)

**Comment by duedal** [comment]
Possible sure, but I am not aware of any SMPP provider software doing so. 

Providers don't strictly keep to the protocol format, but so far our regex seems to be working, and I've gotten a few pull requests with edge cases.

If you have a specific use case, please note the non-compliant provider and open a pull request.
