### ISSUE TITLE
Failed to read reply to command: 0x6

### ISSUE THREAD

**Issue by kumarpratik** [onlinecity/php-smpp#3]
PHP Fatal error:  Uncaught exception 'SmppException' with message 'Failed to read reply to command: 0x6' in smppclient.class.php:619
Stack trace:
#0 smppclient.class.php(150): SmppClient->sendCommand(6, '')
#1 test.php(22): SmppClient->close()
#2 {main}

  thrown in smppclient.class.php on line 619

Fatal error: Uncaught exception 'SmppException' with message 'Failed to read reply to command: 0x6' in smppclient.class.php:619
Stack trace:
#0 smppclient.class.php(150): SmppClient->sendCommand(6, '')
#1 test.php(22): SmppClient->close()
#2 {main}

  thrown in smppclient.class.php on line 619

**Comment by iShift** [comment]
and why it is "FATAL" if it is normal?
