### ISSUE TITLE
 Uncaught exception 'SocketTransportException' 

### ISSUE THREAD

**Issue by maridansoft** [onlinecity/php-smpp#35]
Fatal error: Uncaught exception 'SocketTransportException' with message 'Could not connect to any of the specified hosts' in /home/host1341423/feedbackrussia.ru/htdocs/test/port/gevork/sockettransport.class.php:262 Stack trace: #0 /home/host1341423/feedbackrussia.ru/htdocs/test/port/gevork/test.php(19): SocketTransport->open() #1 {main} thrown in /home/host1341423/feedbackrussia.ru/htdocs/test/port/gevork/sockettransport.class.php on line 262

Why we get this? The SMPP provider says it didnt get any request to given IP from ours. Any ideas? 
I am  giving an IP insitead of hostname, so ip4 could not be the problem .

**Comment by sah-anshu** [comment]
Even i am facing the same problem. Are you been able to solve it.

**Comment by maridansoft** [comment]
nope, seems that the provider had a smart IP based filtering and the SMPP server was not just answering to our tcp calls. check that your calls are really  getting to endpoint.

**Comment by maridansoft** [comment]
I am closing because this was a connectivity issue

**Comment by yerganat** [comment]
Solve the problem by setting
$transport->setSendTimeout(30000);

**Comment by yerganat** [comment]
Solve the problem by setting 
$transport->setSendTimeout(30000);
