### ISSUE TITLE
Bind Failed

### ISSUE THREAD

**Issue by gokcell** [onlinecity/php-smpp#38]
Hi,

I received Bind Failed error. I am sure that my username and passwords are correct. Because when i put wrong user i received "Invalid System ID" and when i put wrong password reveived "Invalid Password" message.

Error log is below.
Kindly your support.

# /usr/bin/php cell.php  
Connecting to x.y.z.t:10000...
Connected to x.y.z.t:10000!
Binding transmitter...
Send PDU         : 48 bytes
 00 00 00 30 00 00 00 02 00 00 00 00 00 00 00 01 49 6e 74 65 72 39 30 33 34 30 00 41 53 57 45 31 34 33 32 00 53 4d 53 30 33 34 30 00 34 01 01 00 
 command_id      : 0x2
 sequence number : 1
Read PDU         : 16 bytes
 00 00 00 10 80 00 00 02 00 00 00 0d 00 00 00 01 
 command id      : 0x80000002
 command status  : 0xd Bind Failed
 sequence number : 1
PHP Fatal error:  Uncaught exception 'SmppException' with message 'Bind Failed' in /root/php-smpp-master/smppclient.class.php:625
Stack trace:
#0 /root/php-smpp-master/smppclient.class.php(482): SmppClient->sendCommand(2, 'username?pass...')
#1 /root/php-smpp-master/smppclient.class.php(137): SmppClient->_bind('username', 'password', 2)
#2 /root/php-smpp-master/cell.php(17): SmppClient->bindTransmitter('username', 'password')
#3 {main}
  thrown in /root/php-smpp-master/smppclient.class.php on line 625

**Comment by duedal** [comment]
Make sure you are using the system type specified by your provider, the default is 'WWW': https://github.com/onlinecity/php-smpp/blob/master/smppclient.class.php#L29
