### ISSUE TITLE
'Failed to read reply to command: 0x2'

### ISSUE THREAD

**Issue by IreneLing** [onlinecity/php-smpp#39]
Hi,

Thanks for your work and currently I'm using it. However I'm facing an error as below:

Fatal error: Uncaught exception 'SmppException' with message 'Failed to read reply to command: 0x2' in /var/www/smpp/smppclient.class.php:620 Stack trace: #0 /var/www/smpp/smppclient.class.php(479): SmppClient->sendCommand(2, 'xxxx?xxxx...') #1 /var/www/smpp/smppclient.class.php(134): SmppClient->_bind('xxxxx', 'xxxxxx', 2) #2 /var/www/smpp/sms.php(18): SmppClient->bindTransmitter('xxxxx', 'xxxxx') #3 {main} thrown in /var/www/smpp/smppclient.class.php on line 620 

Here is my test script:

<?php
require_once 'smppclient.class.php';
require_once 'gsmencoder.class.php';
require_once 'sockettransport.class.php';

// Construct transport and client
$transport = new SocketTransport(array('sms1.xxxxxxx.com'),9000);
$transport->setRecvTimeout(10000);
$transport->setSendTimeout(10000);
$smpp = new SmppClient($transport);

// Activate binary hex-output of server interaction
$smpp->debug = true;
$transport->debug = true;

// Open the connection
$transport->open();
$smpp->bindTransmitter("xxxxx","xxxxx");

// Optional connection specific overrides
SmppClient::$sms_null_terminate_octetstrings = false;
SmppClient::$csms_method = SmppClient::CSMS_PAYLOAD;
//SmppClient::$sms_registered_delivery_flag = SMPP::REG_DELIVERY_SMSC_BOTH;

$smpp->close();

?>

I can see some people having error 0x4 , however I unable to find any thread related to error 0x2.
Please help?Thank you.

**Comment by duedal** [comment]
Command 0x2 is the bind command, since this is the first command you're transmitting the connection is established but you never receive any data. Likely the packets are simply dropped due to connectivity issue. 

Most likely reason is a firewall or you are not connecting on the right port number.

**Comment by IreneLing** [comment]
Thanks for your reply.
I see, the port number is correct so I will contact the sms service provider to check for it.

Thanks again and wish you have a nice day.

**Comment by lillem4n** [comment]
I have the exact same problem. 
I use your libs to test my own SMPP server (kannel). I know the port is right, and I got this log entries from kannel confirming it does connect. But then it hangs for a few seconds and dies:

Kannel log:
2015-01-24 15:26:51 [11529] [2] DEBUG: HTTP: Creating HTTPClient for `127.0.0.1'.
2015-01-24 15:26:51 [11529] [2] DEBUG: HTTP: Created HTTPClient area 0xbd0270.
2015-01-24 15:27:01 [11529] [6] DEBUG: HTTP: Destroying HTTPClient area 0xbd0270.
2015-01-24 15:27:01 [11529] [6] DEBUG: HTTP: Destroying HTTPClient for `127.0.0.1'.

PHP debug backtrace:
Connecting to 127.0.0.1:12010...
Connected to 127.0.0.1:12010!
Binding transmitter...
Send PDU         : 45 bytes
 00 00 00 2d 00 00 00 02 00 00 00 00 00 00 00 01 69 68 61 40 6c 61 72 76 69 74 2e 73 65 00 77 6b 64 6a 6b 63 00 57 57 57 00 34 00 00 00 
 command_id      : 0x2
 sequence number : 1
PHP Fatal error:  Uncaught exception 'SmppException' with message 'Failed to read reply to command: 0x2' in phpsmpp/smppclient.class.php:620
Stack trace:
#0 phpsmpp/smppclient.class.php(479): SmppClient->sendCommand(2, 'username\x00w...')
#1 phpsmpp/smppclient.class.php(134): SmppClient->_bind('username', 'password', 2)
#2 phpsmpp/runtest.php(17): SmppClient->bindTransmitter('username', 'password')
#3 {main}
  thrown in phpsmpp/smppclient.class.php on line 620

**Comment by lillem4n** [comment]
I just verified that it does not work on our live system where our customers are using this in production right now. The problem must be with my test code or with your awsome library. :)

My test code looks as follows:
    require_once('smppclient.class.php');
    require_once('gsmencoder.class.php');
    require_once('sockettransport.class.php');

    $transport = new SocketTransport(array('127.0.0.1'), 12010);
    $transport->setRecvTimeout(10000);
    $smpp = new SmppClient($transport);

    $smpp->debug      = TRUE;
    $transport->debug = TRUE;

    $transport->open();
    $smpp->bindTransmitter('username', 'password');

    $message = 'simple test';
    $from = new SmppAddress('test', SMPP::TON_ALPHANUMERIC);
    $to = new SmppAddress(46709771337, SMPP::TON_INTERNATIONAL, SMPP::NPI_E164);

    $smpp->sendSMS($from, $to, $message);

    $smpp->close();

**Comment by imuneer** [comment]
I am having the exact same issue. @lillem4n any luck?

**Comment by lillem4n** [comment]
No, sorry. :(

**Comment by ritmas** [comment]
@lillem4n have you tried enabling `$transport->setSendTimeout(10000);` next to `setRecvTimeout()`?

If that won't fix the problem, catch some packets and analyze them with [Wireshark](https://www.wireshark.org).
By default, it recognizes most of SMPP packets, so it might be useful info for debugging.

For generating [pcap](https://en.wikipedia.org/wiki/Pcap) file I'd use something like that:
```tcpdump -s 0 -i eth1 -w tcpdump.pcap -A host 127.0.0.1```

**Comment by imuneer** [comment]
I could be able to make it work with this light weight library.

http://sourceforge.net/projects/phpsmppapi/?source=typ_redirect

**Comment by imuneer** [comment]
I got this library working by adjusting the Sender ID and the SourceTON values.

**Comment by Sukhrob** [comment]
I am having the same problem. My provider only supports transceiver. But, I am only binding a transmitter. Do I also have to implement receiver?

**Comment by ritmas** [comment]
@Sukhrob I had same issue. SMPP 3.4 supports `transceiver`, but repo has not this feature. I have live version of it, but didn't pushed PR yet. I can create one later today, though it's pretty simple to implement on your own.

**Comment by Sukhrob** [comment]
That would be great if you did. I will be looking forward to it. Thanks @ritmas.

**Comment by Sukhrob** [comment]
Thanks @ritmas for the PR and I am on it. But, I don't understand why the author @duedal hasn't implemented the transceiver mode if it is quite simple to do so.

**Comment by duedal** [comment]
@Sukhrob Transceiver is a separate issue. This library is a thin protocol client, and may be used as part of a bigger project, using transceiver implies asynchronous communication which can be very tricky. I will respond to @ritmas PR at the PR #46

**Comment by Sukhrob** [comment]
Thanks for your quick response @duedal. I will be looking forward to it.

**Comment by duedal** [comment]
@imuneer Great to hear you got it working
@lillem4n I notice your log for kannel reads HTTP client, are you sure you're connecting the right way, and not connecting a SMPP client to a HTTP server?

As I stated earlier 0x2 is the first command sent out on a new socket, and if there is an issue reading the reply, this is a connection issue, which can be caused by many things, but so far is not an issue with this library.

**Comment by imuneer** [comment]
My SMS provider asked me to change the properties in file `class SmppClient`

`public static $system_type="WWW";`

to

`public static $system_type="XXXXX";  // an specific one which they gave me` 

and some adjustment on source TON and source NPI.
@duedal

**Comment by nasznjoka** [comment]
I had to set both $transport->setRecvTimeout(10000);
and $transport->setSendTimeout(10000) for it to work

**Comment by ruslankovalov** [comment]
In my case IP address had to be white-listed on smpp server side. That resolved the issue.
