### ISSUE TITLE
No delivery report 

### ISSUE THREAD

**Issue by IreneLing** [onlinecity/php-smpp#40]
Hi,sorry for another question.
I sent few sms and received all of them. When I tried to retrieve the delivery reports with the sample code given, it has error 'Could not connect to any of the specified hosts', so I added 
$transport->setSendTimeout(60000);

but there is no delivery reports available. It returns 'SMS: bool(false)'

I already added SmppClient::$sms_registered_delivery_flag = SMPP::REG_DELIVERY_SMSC_BOTH; 
in my send sms PHP file.

Anything I missed out? Sorry again and thanks.

**Comment by IreneLing** [comment]
Here is my send sms PHP file:

// Construct transport and client
$transport = new SocketTransport(array('sms1.xxxxxxx.com'),9000);
$transport->setRecvTimeout(10000);
$transport->setSendTimeout(10000);
$smpp = new SmppClient($transport);

// Activate binary hex-output of server interaction
$smpp->debug = true;
$transport->debug = true;

// Open the connection
$transport->open();
$smpp->bindTransmitter("xxxxx","xxxxx");

// Optional connection specific overrides
SmppClient::$sms_null_terminate_octetstrings = false;
SmppClient::$csms_method = SmppClient::CSMS_PAYLOAD;
SmppClient::$sms_registered_delivery_flag = SMPP::REG_DELIVERY_SMSC_BOTH;


// Prepare message
$message = 'Happy';
$encodedMessage = GsmEncoder::utf8_to_gsm0338($message);
$from = new SmppAddress('880088',SMPP::TON_NATIONAL);
$to = new SmppAddress(xxxxxxx,SMPP::TON_NATIONAL,SMPP::NPI_NATIONAL);

// Send
$smpp->sendSMS($from,$to,$encodedMessage,$tags);

// Close connection
$smpp->close();

**Comment by IreneLing** [comment]
Sorry due to my outdated browser I unable to edit the first comment.
After I set 
$transport->setRecvTimeout(120000);
$transport->setSendTimeout(120000);
,here is the error:

SMS: bool(false) here Fatal error: Uncaught exception 'SmppException' with message 'Failed to read reply to command: 0x6' in /var/www/smpp/smppclient.class.php:620 Stack trace: #0 /var/www/smpp/smppclient.class.php(150): SmppClient->sendCommand(6, '') #1 /var/www/smpp/sms2.php(26): SmppClient->close() #2 {main} thrown in /var/www/smpp/smppclient.class.php on line 620

**Comment by IreneLing** [comment]
Sorry here is another updates.

After I changed the bindTransmitter to bindReceiver, I able to get the delivery receipt now.

Sorry for the troubles and thank you.

**Comment by Angelababy22** [comment]
> 抱歉，这是另一个更新。
> 
> 在将bindTransmitter更改为bindReceiver之后，我现在可以获取收货收据。
> 
> 对不起，给您带来的麻烦，谢谢。

Can you share SMPP PHP with me to get the delivery report? I need it very much and, of course, I'll pay for it
