### ISSUE TITLE
Send SMS parameters

### ISSUE THREAD

**Issue by Sogl** [onlinecity/php-smpp#47]
Hi!

My operator gave me instructions with some parameters for send messages signed by the sender:
* source_addr_ton = 5 
* source_addr_npi = 0 
* dest_addr_ton = 1 
* dest_addr_npi = 1 

Where I need to put them in my php file?

**Comment by Ang3r** [comment]
@Sogl, you should set them as second and third argument when initializing `SmppAddress()`:

```php
$from = new SmppAddress('**from**', SMPP::TON_ALPHANUMERIC, SMPP::NPI_UNKNOWN);
$to = new SmppAddress('**to**', SMPP::TON_INTERNATIONAL, SMPP::NPI_E164);
```

**Comment by duedal** [comment]
Thanks @Ang3r
