### ISSUE TITLE
smpp connection issue 

### ISSUE THREAD

**Issue by praxxs** [onlinecity/php-smpp#53]
I can't connect to the smpp server, here's the error message : 

Fatal error: Uncaught exception 'SocketTransportException' with message 'Could not connect to any of the specified hosts' in /xxxxxxxxxx/www/smpp/sockettransport.class.php:262 Stack trace: #0 /xxxxxxxxxx/www/smpp/receive_sms.php(17): SocketTransport->open() #1 {main} thrown in /xxxxxxxxxx/www/smpp/sockettransport.class.php on line 262 

I changed the socket transport to SocketTransport::$forceIpv4=true; still no connection to the server

**Comment by Shimmi** [comment]
Hi @praxxs,
Can you try steps mentioned in [this issue/comment](https://github.com/onlinecity/php-smpp/issues/50#issuecomment-188198086) If the issue is still valid or close it otherwise?

Thanks!

**Comment by yerganat** [comment]
Solve the problem by setting
$transport->setSendTimeout(30000);
