### ISSUE TITLE
$transport->open() fails

### ISSUE THREAD

**Issue by ruturaaj** [onlinecity/php-smpp#83]
I am trying to run the example code with my SMPP credentials. The example code fails to send SMS; debugging shows it does not go beyond $transport->open() line. No error shown; no error is logged. I have successfully executed another script which runs in transceiver mode, so I'm sure the server setup running SMPP Client script is good. 

Please guide me to run the example code mentioned here.

**Comment by ruturaaj** [comment]
I found it was problem with Linux File Permissions. It's working good for English Messages.

**Comment by zkenstein** [comment]
Hi @ruturaaj can you please share the code using transceiver? Thx

**Comment by ruturaaj** [comment]
> 
> 
> Hi @ruturaaj can you please share the code using transceiver? Thx

Here goes my code. Sorry, I've just copied the code as it is from my Application's SMS Class. But I'm sure you will get an idea of how the things work...

           `$transport = new TSocket($smpp_config['Server'],$smpp_config['Port']);
            $transport->setRecvTimeout(10000);
            $transport->setSendTimeout(10000);

            $smpp = new SmppClient($transport);

            // Activate binary hex-output of server interaction
            $smpp->debug = false;

            // Open the connection
            $transport->open();

            //Bind
            $smpp->bindTransmitter($smpp_config['Username'], $smpp_config['Password']);

            /*delivery report and other configuration*/
            SmppClient::$sms_null_terminate_octetstrings = false;
            SmppClient::$sms_use_msg_payload_for_csms = true;
            SmppClient::$sms_registered_delivery_flag = \SMPP\REG_DELIVERY_SMSC_BOTH;

            //prepare message
            $message = $job['Message'];
            if ($job['MessageType'] == 'Unicode') {
                $encoding = mb_detect_encoding($message);
                $message = iconv($encoding,'UTF-16BE',$message);
                $encodedMessage = $message;
                $isUnicode = true;
            }
            else {
                $encodedMessage = $message;
                $isUnicode = false;
            }

            //sanitize sender id
            $sender_id = filter_var( $job['SenderID'], FILTER_SANITIZE_STRING);
            //$sender_id = 'RUTURJ';
            $from = new \SMPP\Address($sender_id,\SMPP\TON_ALPHANUMERIC);

            //create smpp address to send sms
            $mobile = filter_var($mobile, FILTER_SANITIZE_NUMBER_INT);
            $to = new \SMPP\Address($mobile,\SMPP\TON_INTERNATIONAL,SMPP\NPI_E164);

            $tags = "";

            if ($isUnicode) {
                   $output = $smpp->sendSMS($from,$to,$encodedMessage,$tags, \SMPP\DATA_CODING_UCS2);
            }
            else {
                    $output = $smpp->sendSMS($from,$to,$encodedMessage,$tags, \SMPP\DATA_CODING_DEFAULT);
            }

            if ($output['msgid'] != '') {
                      //message sent.
            }
`

**Comment by ruturaaj** [comment]
> 
> 
> Hi @ruturaaj can you please share the code using transceiver? Thx

Sorry for the late reply mate. 

Well, I'm not using this class in my application. I remember I made this class to send SMS in Transiver mode; but I don't have that code with me right now. I will try to find it tomorrow, and if I get it, I will surely share that with you here.
